name: Quality Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint-prettier-type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run prettier check
        run: npm run prettier:check

      - name: Run type-check
        run: npm run type-check
